project:
  name: quickstart-compliance-cjis
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-southeast-1
  s3_bucket: ''
tests:
  compl-cjis:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      pAvailabilityZones: $[taskcat_getaz_2]
      pDBPassword: $[taskcat_genpass_26]
      pEC2KeyPair: $[taskcat_getkeypair]
      pEC2KeyPairBastion: $[taskcat_getkeypair]
      pNotifyEmail: distlist@example.org
      pSupportsConfig: 'false'
      pVPCTenancy: default
    regions:
    - ap-southeast-1
    s3_bucket: ''
    template: templates/main.template.yaml

